apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: sts-app
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin



---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: sts-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongoexpress
  namespace: sts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nslookup mongodb.default.svc.cluster.local; do echo waiting for mongodb; sleep 2; done;']
     
      containers:
        - image: mongo-express
          imagePullPolicy: IfNotPresent
          name: mongoexpress
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-svc
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: admin
            - name: ME_CONFIG_SITE_BASEURL
              value: /mongoexpress

---

apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-svc
  namespace: sts-app
spec:
  type: NodePort
  selector:
    app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32504
