apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app
  namespace: sts-app
  labels:
    name: node-app
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: node-app
      labels:
        app: node-app
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nslookup mongodb.sts-app.svc.cluster.local; do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: node-app
          image: gudditi/node-app
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: node-app-secret
          resources:
            requests:
              cpu: "60m"
              memory: "60Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
