apiVersion: v1
kind: Service 
metadata:
  name: node-svc
  namespace: sts-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31143