apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    name: node-app
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: node-app
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gudditi/node-app
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: node-app-secret
          resources:
            requests:
              cpu: "60m"   # Note: "m" is lowercase for milliCPU (100m instead of 100M)
              memory: "60Mi"
            limits:
              cpu: "100m"   # Note: "m" is lowercase for milliCPU (250m instead of 250M)
              memory: "100Mi"
