apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - name: nginx-deploy
          image: gudditi/nginx-pod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    app: nginx-service

spec:
  type: NodePort
  selector:
    app: nginx-deploy
  ports:
    - name: nginx-service 
      protocol: TCP
      port: 80
      targetPort: 80
      
