apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gudditi/monkey:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: monkey-app
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - name: tcp
      port: 80
      targetPort: 80
