apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - image: mongo-express
          imagePullPolicy: IfNotPresent
          name: mongoexpress
          ports:
            - containerPort: 8081
          env:
            - name:  ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: USERNAME

            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: PASSWORD

            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SERVER

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  labels:
    app: mongo-express
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
