# pod1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
        - name: pod1
          image: busybox:1.36
          command: ["sleep", "3600"]  # Optional command to keep the container running

---
# pod1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: pod1
  ports:
    - protocol: TCP
      port: 80
---
# pod2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
        - name: pod2
          image: busybox:1.36
          command: ["sleep", "3600"]  # Optional command to keep the container running

---
# pod2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pod2-service
spec:
  selector:
    app: pod2
  ports:
    - protocol: TCP
      port: 80
