apiVersion: apps/v1
kind: Deployment 
metadata:
  name: node-app
  labels: 
    name: node-app
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: node-app
      labels: 
        app: node-app
    spec:
      containers:
        - name: node-app
          image: gudditi/node-app
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: node-config-map


